from typing import Protocol, runtime_checkable, Any


@runtime_checkable
class MouseTool(Protocol):
    """
    Protocol for tools that handle mouse interaction and optional drawing
    in a PyQt/PySide context.
    """

    def mouseMove(self, *args: Any, **kwargs: Any) -> None: ...
    def mousePress(self, *args: Any, **kwargs: Any) -> None: ...
    def mouseRelease(self, *args: Any, **kwargs: Any) -> None: ...
    def mouseDoubleClick(self, *args: Any, **kwargs: Any) -> None: ...

    def draw(self, qp, *args: Any, **kwargs: Any) -> None: ...
    def getToolName(self) -> str: ...
    def getToolTip(self) -> str: ...